[package]
name = "ai-desktop-automation"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
log = { version = "0.4.22", features = ["std"] }
windows = { version = "0.58.0", features = ["Win32_System_Com", "Win32_UI_Accessibility", "Win32_UI_WindowsAndMessaging"] }
